import { globSync } from 'glob';
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';

const paths = globSync(['./src/**/*.ts', '!./src/**/*.d.ts', './src/**/*.vue']);
console.log(paths);

// https://vitejs.dev/config/
// Note: Declaration files are generated by vue-tsc using tsconfig.build.json
export default defineConfig({
	base: './',
	plugins: [
		vue(),
	],
	resolve: {
		alias: {
			'@': '/src',
		},
	},
	build: {
		minify: false,
		emptyOutDir: true,
		sourcemap: true,
		rollupOptions: {
			external: ['vue', 'primevue', 'primeicons', '@kaosdlanor/kanim', '@kaosdlanor/vue-reactivity', '@packages/data'],
			output: {
				dir: './dist',
				format: 'es',
				entryFileNames: '[name].mjs',
				preserveModules: true,
				preserveModulesRoot: './src',
				exports: 'named',
				globals: {
					vue: 'Vue',
					primevue: 'PrimeVue',
					primeicons: 'PrimeIcons',
				},
			},
		},
		lib: {
			entry: [
				...paths,
			],
			formats: ['es'],
		}
	},
})
